@startuml

!theme plain

package model{

	class Leaf {
		value
		refs
	}

	class Ref {
		source : Leaf
		set value
		update()
	}

	Leaf *-- Ref
	Refs o-- Ref

	class ArrayModel

	class Node {
		id
		tree
		name
		com
		Parts
	}

	class Tree {
		root
	}

	Tree *-- Node
	Tree --o Node
	Node *-- Node
}

package model.navi {

	class Index
	
	class Selector {
		root
		current
	}

	class Navi {
		url
		setUrl()
	}

	Selector *-- Index
	Selector --o Index
	Index *- Index
	Navi -|> Selector
}

package htdom {

	class Component
	class Parts

	Component *-- Parts
}
